Added update site for Gut Analysis Toolbox
imagej/list-of-update-sites pull request #107
Opened 2022-03-30 19:37 UTC by pr4deepr

Hi
  I would like to add my software Gut Analysis Toolbox to the list of update sites please. 
Thank you.

Cheers
Pradeep

2022-03-30 21:40 UTC, ctrueden requested changes
@pr4deepr Thanks!

There is an error with a missing leading square bracket in your Markdown description. Could you please fix that?

Also, could you please create a page on imagej.net for your plugin(s)? It's up to you whether you populate it fully, or just make stubs linking off to your GitHub wiki docs (although I personally wish more of the community would unify around the ImageJ wiki so that users can actually find stuff more easily).

2022-03-30 23:46 UTC, pr4deepr commented on sites.yml
> +      Gut Analysis Toolbox](https://github.com/pr4deepr/GutAnalysisToolbox/wiki) enables semi-automated analysis of
Created a pull request:
https://github.com/imagej/list-of-update-sites/pull/107/commits/376d9bac05fe12d8fc0b7fe44f2b5af06731e737

2022-03-30 23:48 UTC, pr4deepr commented on sites.yml
> +      - "[Pradeep Rajasekhar](mailto:pradeep.rajasekhar@gmail.com)"
Thanks
Created a pull request..
https://github.com/imagej/imagej.github.io/pull/227
I wasn't aware of creating pages in imagej.net.. I'd prefer that than github as its easier to discover..

2022-03-31 02:00 UTC, merged

2022-03-31 02:01 UTC, ctrueden commented
@pr4deepr Great, thanks!