Update sites.yml added with MultistackReg
imagej/list-of-update-sites pull request #113
Opened 2022-05-24 07:18 UTC by miura

Update sites.yml edited with an addition of MultistackReg, a new update site recently created.

2022-05-25 08:53 UTC, imagejan reviewed
Thanks @miura for maintaining MultiStackReg and making it available! May I ask you to add some minimal documentation to the ImageJ wiki as a new page for MultiStackReg?

2022-05-25 08:53 UTC, imagejan commented on sites.yml
> +      - "[Kota Miura](https://imagej.net/User:Miura)"
URLs for user pages on the wiki changed with the switch to GitHub pages, so let's use the updated URL instead of relying on the redirect:

```suggestion
      - "[Kota Miura](https://imagej.net/people/cmci)"
```

2022-05-25 08:53 UTC, imagejan commented on sites.yml
> +      [MultiStackReg](https://sites.imagej.net/MultiStackReg/)
Instead of pointing to the hosted files, the description should rather point to documentation of the plugin. I suggest creating https://imagej.net/plugins/multistackreg and pointing to it here.

```suggestion
      [MultiStackReg](https://imagej.net/plugins/multistackreg)
```

2022-05-25 15:32 UTC, ctrueden requested changes
I second both of @imagejan's suggestions. Please create a wiki page, and link to it from the description. And please use the current imagej.net people page URL.

2022-05-25 21:08 UTC, ctrueden commented
@miura If it saves you time, I can create the wiki page, and also change the link in this PR. But I do not feel qualified to actually populate the wiki page with content. Let me know if there's anything I can do to make your life easier.

Tangentially, I noticed that you removed the `github: miura` line from your `people/cmci` page. If you like, we can instead rename this page to `people/miura` and then I can redirect `people/cmci` on the server side to the new destination, so that old links do not 404. What do you think?

2022-05-26 08:03 UTC, miura commented
Hi @ctrueden , yes, it would be great to rename the file and also redirect `people/cmci` to `people/miura`. Thanks a lot!

Hi @imagejan , I committed your changes, and will update the link to the maintainer link after Curtis makes the above updates. Thanks!

2022-05-26 18:48 UTC, ctrueden commented
@miura I added the redirect from `/people/cmci` to `/people/miura`, and tidied up the `/plugins/multistackreg` page. And I update cmci to miura on this PR. All looks good to merge now.

2022-05-26 18:49 UTC, merged

2022-05-27 00:43 UTC, miura commented
Thanks @ctrueden !