Update sites.yml
imagej/list-of-update-sites pull request #142
Opened 2023-11-16 07:55 UTC by EdenTamrat

Hello, I am looking add my update site onto the sites.yml list.

2023-11-16 23:33 UTC, ctrueden requested changes

2023-11-16 23:33 UTC, ctrueden commented on sites.yml
> +      https://github.com/EdenTamrat/imagej.github.io/blob/1069c0beda8e4f0d5bd70e055b5a294446efca6b/_pages/plugins/Nscale-segmentation.md
This URL should be `https://imagej.net/plugins/Nscale-segmentation`, and it should be made into a hyperlink with Markdown syntax.

2023-11-16 23:36 UTC, ctrueden commented
Thanks @EdenTamrat. I will fix my comment above post-merge, so don't worry about fixing it yourself. :smile:

2023-11-16 23:38 UTC, ctrueden commented
Actually... before I merge this: @EdenTamrat I noticed that the name of the update site is `Nscale_segmentaion` rather than `Nscale-segmentation`. Shall we rename the update site to fix this typo, before adding it to the advertised list? Or is that spelling intentional?

2023-11-17 17:54 UTC, EdenTamrat commented
Hello, thank you for your comments. 
The typo was unintentional; I meant to write Nscale_segmentation like you mentioned. 
I would like to rename my update site to fix the error, if its possible.

2024-02-14 20:45 UTC, closed without merging

2024-02-14 20:49 UTC, hinerm commented
@EdenTamrat I renamed the [update site](https://sites.imagej.net/Nscale_segmentation/) and then updated your PR. For reasons I don't understand I was able to update your PR once but it updated to the current `main` instead of the corrected PR. So I just pushed the changes. Apologies for blowing away your PR. If you need anything else though please let me know.

2024-02-20 16:24 UTC, ctrueden commented
Thanks @hinerm for dealing with this, and sorry @EdenTamrat for dropping the ball on it for so long. Please let us know if you encounter any issues with using the update site!