Add microglia morphometry
imagej/list-of-update-sites pull request #97
Opened 2021-12-17 13:34 UTC by tischi

2021-12-17 21:06 UTC, imagejan requested changes
This looks like wild copy-and-paste to me, with additions of the same information in several places. @tischi can you please make sure the .yml file stays intact?
(We should have checks in place on our continuous integration (GitHub Actions), but they're temporarily not working due to the move from Travis to GitHub (see https://github.com/imagej/list-of-update-sites/issues/91). Otherwise the CI would have caught this messed up yml syntax.)

2021-12-17 21:06 UTC, imagejan commented on sites.yml
> +      - "  - name: "BigDataProcessor"
There's something wrong here, you deleted part of the previous entry.

2021-12-17 21:06 UTC, imagejan commented on sites.yml
> +git@github.com:imagej/list-of-update-sites.git
???

2021-12-17 21:06 UTC, imagejan commented on sites.yml
> +      linked to a specific biological problem and can be applie  - name: "BigDataProcessor"
Some information got deleted here.

2021-12-17 21:06 UTC, imagejan commented on sites.yml
> +      - "[Christian Tischer](mailto:christian.tischer@embl.de)"d to a large
??

2021-12-18 11:57 UTC, tischi commented
This is very weird as I did not touch those regions at all...
I will check!

2021-12-18 12:06 UTC, closed without merging

2021-12-18 12:08 UTC, tischi commented
There is something screwed up. I'll delete this branch and make a new PR.